beautifulsoup4>=4.9.3
dash>=1.21.0
elasticsearch>=7.14.0
exifread>=2.3.2
flask>=2.0.1
gensim>=4.1.0
jsonschema>=3.2.0
langdetect>=1.0.9
matplotlib>=3.4.3
networkx>=2.6.3
nltk>=3.6.3
numpy>=1.21.0
OCRmyPDF>=12.7.2
openpyxl>=3.0.9
pandas>=1.3.0
pdfplumber>=0.5.28
Pillow>=8.3.1
plotly>=5.3.1
psycopg2-binary>=2.9.1
py2neo>=2021.2.3
PyMuPDF>=1.18.14
python-docx>=0.8.11
pytesseract>=0.3.8
regex>=2021.8.28
requests>=2.26.0
scikit-learn>=0.24.2
scipy>=1.7.1
seaborn>=0.11.2
spacy>=3.1.3
sqlalchemy>=1.4.22
streamlit>=0.87.0
textract>=1.6.4
